In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
arr=np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr=np.linspace(1,5,3)
print(arr)

[1. 3. 5.]


In [15]:
import random as re
np.random.rand(5)

array([0.32278159, 0.7767063 , 0.99539116, 0.19069264, 0.96223568])

In [ ]:
np.random.randn(6)

array([-0.65528253,  1.28359945, -0.76364543, -0.63885865,  0.63745065,
       -0.48072494])

In [18]:
np.random.randint(10,20,10)

array([10, 13, 17, 10, 15, 18, 13, 18, 17, 12], dtype=int32)

In [19]:
# Array Attriutes
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(9)

In [25]:
arr.sum()

np.int64(45)

In [26]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [28]:
arr.argmax()

np.int64(8)

In [35]:
arr= np.arange(1,31)

In [36]:
arr=arr.reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [3]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#print row
arr[3]


array([16, 17, 18, 19, 20])

In [ ]:
#Sub grid
sGrid=arr[0:2,1:3]
sGrid

array([[2, 3],
       [7, 8]])

In [7]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [8]:
# Boolean indexing
arr=np.arange(11,21)
bool_idx=arr%2==0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

### Array Operations

In [11]:
#Arithmetic Operations
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

summ=a1+a2
print(summ)
subb=a1-a2
print(subb)
mul=a1*a2
print(mul)
divv=a1/a2
print(divv)
print(a1//a2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 0 0 0 0]


In [12]:
# Broadcasting
l=[10,20,30,40,50]
a=np.array(l)
print(a+10)

[20 30 40 50 60]


In [13]:
# Deep and shallow copy
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice=a[:5]
print(slice*9)


[ 9 18 27 36 45]


In [3]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

# To take product of two matrices
product=np.dot(A,B)
print(product)

[[19 22]
 [43 50]]


In [5]:
#Transpose of a matrix
transpose=np.transpose(A)
print(transpose)
#OR
transpose=A.T
print(transpose)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [ ]:
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
#Stacking of arrays
# For stacking we need to use vectors we cannot use matrices
stack=np.stack((A,B),axis=0)
print(stack) # Horizontal stacking
stack=np.stack((A,B),axis=1)
print(stack) # Vertical stacking


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [9]:
# 2nd method
np.vstack((A,B))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
np.hstack((A,B))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.column_stack((A,B))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])