In [4]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
arr=np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr=np.linspace(1,5,3)
print(arr)

[1. 3. 5.]


In [15]:
import random as re
np.random.rand(5)

array([0.32278159, 0.7767063 , 0.99539116, 0.19069264, 0.96223568])

In [ ]:
np.random.randn(6)

array([-0.65528253,  1.28359945, -0.76364543, -0.63885865,  0.63745065,
       -0.48072494])

In [18]:
np.random.randint(10,20,10)

array([10, 13, 17, 10, 15, 18, 13, 18, 17, 12], dtype=int32)

In [19]:
# Array Attriutes
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr.size

9

In [22]:
arr.dtype

dtype('int64')

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.max()

np.int64(9)

In [25]:
arr.sum()

np.int64(45)

In [26]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [28]:
arr.argmax()

np.int64(8)

In [35]:
arr= np.arange(1,31)

In [36]:
arr=arr.reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])